// Mock data for CEO demo
export const mockUsers = [
  { id: 'user1', email: 'sarah.johnson@techcorp.com', name: 'Sarah Johnson' },
  { id: 'user2', email: 'mike.chen@startup.io', name: 'Mike Chen' },
  { id: 'user3', email: 'emily.davis@company.com', name: 'Emily Davis' },
  { id: 'user4', email: 'alex.rodriguez@biz.com', name: 'Alex Rodriguez' },
  { id: 'user5', email: 'jessica.kim@tech.io', name: 'Jessica Kim' },
];

export const mockMemes = [
  {
    id: 'meme1',
    imageUrl: 'https://i.imgflip.com/30b1gx.jpg',
    userId: 'user1',
    userEmail: 'sarah.johnson@techcorp.com',
    labels: [
      {
        id: 'label1',
        text: 'WHEN THE CLIENT SAYS',
        x: 50,
        y: 10,
        fontSize: 32,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
      {
        id: 'label2',
        text: '"JUST A SMALL CHANGE"',
        x: 50,
        y: 80,
        fontSize: 32,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
    ],
    createdAt: Date.now() - 3600000, // 1 hour ago
    votesCount: 142,
  },
  {
    id: 'meme2',
    imageUrl: 'https://i.imgflip.com/1ur9b0.jpg',
    userId: 'user2',
    userEmail: 'mike.chen@startup.io',
    labels: [
      {
        id: 'label1',
        text: 'DEBUGGING AT 3 AM',
        x: 50,
        y: 15,
        fontSize: 28,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
      {
        id: 'label2',
        text: 'FINDING THE BUG',
        x: 50,
        y: 75,
        fontSize: 28,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
    ],
    createdAt: Date.now() - 7200000, // 2 hours ago
    votesCount: 98,
  },
  {
    id: 'meme3',
    imageUrl: 'https://i.imgflip.com/1g8my4.jpg',
    userId: 'user3',
    userEmail: 'emily.davis@company.com',
    labels: [
      {
        id: 'label1',
        text: 'PRODUCTION IS DOWN',
        x: 50,
        y: 10,
        fontSize: 30,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
      {
        id: 'label2',
        text: 'IT WORKS ON MY MACHINE',
        x: 50,
        y: 82,
        fontSize: 26,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
    ],
    createdAt: Date.now() - 10800000, // 3 hours ago
    votesCount: 215,
  },
  {
    id: 'meme4',
    imageUrl: 'https://i.imgflip.com/9ehk.jpg',
    userId: 'user4',
    userEmail: 'alex.rodriguez@biz.com',
    labels: [
      {
        id: 'label1',
        text: 'SENIOR DEVELOPER',
        x: 20,
        y: 15,
        fontSize: 24,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'left',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
      {
        id: 'label2',
        text: 'JUNIOR DEVELOPER',
        x: 70,
        y: 15,
        fontSize: 24,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
      {
        id: 'label3',
        text: 'STACKOVERFLOW',
        x: 50,
        y: 75,
        fontSize: 28,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
    ],
    createdAt: Date.now() - 14400000, // 4 hours ago
    votesCount: 187,
  },
  {
    id: 'meme5',
    imageUrl: 'https://i.imgflip.com/4t0m5.jpg',
    userId: 'user5',
    userEmail: 'jessica.kim@tech.io',
    labels: [
      {
        id: 'label1',
        text: 'WHEN YOU FIX ONE BUG',
        x: 50,
        y: 10,
        fontSize: 28,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
      {
        id: 'label2',
        text: 'AND CREATE THREE MORE',
        x: 50,
        y: 80,
        fontSize: 28,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
    ],
    createdAt: Date.now() - 18000000, // 5 hours ago
    votesCount: 156,
  },
  {
    id: 'meme6',
    imageUrl: 'https://i.imgflip.com/26am.jpg',
    userId: 'user1',
    userEmail: 'sarah.johnson@techcorp.com',
    labels: [
      {
        id: 'label1',
        text: 'CODE REVIEW COMMENTS',
        x: 50,
        y: 15,
        fontSize: 26,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
      {
        id: 'label2',
        text: '"LOOKS GOOD TO ME"',
        x: 50,
        y: 75,
        fontSize: 26,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
    ],
    createdAt: Date.now() - 21600000, // 6 hours ago
    votesCount: 89,
  },
  {
    id: 'meme7',
    imageUrl: 'https://i.imgflip.com/1bij.jpg',
    userId: 'user3',
    userEmail: 'emily.davis@company.com',
    labels: [
      {
        id: 'label1',
        text: 'MEETINGS THAT COULD',
        x: 50,
        y: 8,
        fontSize: 30,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
      {
        id: 'label2',
        text: 'HAVE BEEN AN EMAIL',
        x: 50,
        y: 82,
        fontSize: 30,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
    ],
    createdAt: Date.now() - 28800000, // 8 hours ago
    votesCount: 234,
  },
  {
    id: 'meme8',
    imageUrl: 'https://i.imgflip.com/3oevdk.jpg',
    userId: 'user2',
    userEmail: 'mike.chen@startup.io',
    labels: [
      {
        id: 'label1',
        text: 'WHEN YOUR CODE WORKS',
        x: 50,
        y: 12,
        fontSize: 26,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
      {
        id: 'label2',
        text: "BUT YOU DON'T KNOW WHY",
        x: 50,
        y: 78,
        fontSize: 26,
        fontWeight: 900,
        color: '#ffffff',
        textAlign: 'center',
        fontFamily: 'Impact',
        textStroke: '2px black',
      },
    ],
    createdAt: Date.now() - 36000000, // 10 hours ago
    votesCount: 176,
  },
];

export const mockVotes = [
  { id: 'vote1', memeId: 'meme1', userId: 'user2', value: 1, createdAt: Date.now() - 3000000 },
  { id: 'vote2', memeId: 'meme1', userId: 'user3', value: 1, createdAt: Date.now() - 3100000 },
  { id: 'vote3', memeId: 'meme2', userId: 'user1', value: 1, createdAt: Date.now() - 6000000 },
  { id: 'vote4', memeId: 'meme3', userId: 'user4', value: 1, createdAt: Date.now() - 9000000 },
  { id: 'vote5', memeId: 'meme3', userId: 'user5', value: 1, createdAt: Date.now() - 9100000 },
  { id: 'vote6', memeId: 'meme4', userId: 'user1', value: 1, createdAt: Date.now() - 12000000 },
  { id: 'vote7', memeId: 'meme5', userId: 'user2', value: 1, createdAt: Date.now() - 15000000 },
  { id: 'vote8', memeId: 'meme7', userId: 'user1', value: 1, createdAt: Date.now() - 24000000 },
  { id: 'vote9', memeId: 'meme7', userId: 'user4', value: 1, createdAt: Date.now() - 24100000 },
  { id: 'vote10', memeId: 'meme8', userId: 'user3', value: 1, createdAt: Date.now() - 30000000 },
];

